name: Haiku 3.5

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-python:
    uses: ./.github/workflows/test-base-simple.yml
    with:
      llm_model: claude-3-5-haiku-latest
      llm_base_url: https://api.anthropic.com/v1/
      llm_api_key_name: ANTHROPIC_API_KEY
    secrets: inherit